/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.2.3-41-g9ffcbf1db9"
#endif /* AVUTIL_FFVERSION_H */
